/*
******************************************************************************
File:     main.cpp
Info:     Generated by Atollic TrueSTUDIO(R) 7.0.0   2016-12-18

The MIT License (MIT)
Copyright (c) 2009-2016 Atollic AB

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************
*/

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"

#include "DebugUtilities/Debug.hpp"
extern "C" {
	#include "User_USART_lib.h"
}


/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
extern volatile uint8_t uart_received_message_flag;

/* Private function prototypes */
/* Private functions */
void send_char_UART2(char c)
{
	while (USART_GetFlagStatus(USART2, USART_FLAG_TXE) == RESET);
	USART_SendData(USART2, c);
}

void send_string_UART2(char const *s)
{
	while (*s != DELIMETER && *s != 0)
	send_char_UART2(*s++);
}

void clearBuffer(uint8_t * buffer, uint8_t size){
	for(int i=0; i<size; i++){
		buffer[i] = 0;
	}
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  /**
  *  IMPORTANT NOTE!
  *  See the <system_*.c> file and how/if the SystemInit() function updates 
  *  SCB->VTOR register. Sometimes the symbol VECT_TAB_SRAM needs to be defined 
  *  when building the project if code has been located to RAM and interrupts 
  *  are used. Otherwise the interrupt table located in flash will be used.
  *  E.g.  SCB->VTOR = 0x20000000;  
  */

  /**
  *  At this stage the microcontroller clock setting is already configured,
  *  this is done through SystemInit() function which is called from startup
  *  file (startup_stm32l1xx_hd.s) before to branch to application main.
  *  To reconfigure the default setting of SystemInit() function, refer to
  *  system_stm32l1xx.c file
  */


   /*
    * Inicjalizacja diody.
    */
   GPIO_InitTypeDef LD2_Pin;

   GPIO_StructInit(&LD2_Pin);
   LD2_Pin.GPIO_Pin = GPIO_Pin_5;
   LD2_Pin.GPIO_Mode = GPIO_Mode_OUT;

   GPIO_Init(GPIOA, &LD2_Pin);

   GPIO_SetBits(GPIOA, GPIO_Pin_5);
   /***********************************************
   * USART2 Configuration
   ***********************************************/

   init_UART2();

   char message[UART_RX_BUF_SIZE];

  /* Infinite loop */
  while (1)
  {
	  if(uart_received_message_flag){
		  uart_getMessage((uint8_t*)message);
		  send_string_UART2("Otrzymana wiadomosc: ");
		  send_string_UART2(message);
		  send_string_UART2("\n\r");
		  clearBuffer((uint8_t*)message,UART_RX_BUF_SIZE);	// Clears the message buffer so if the new message is shorter than previous, we don't see the remains of the latter
		  uart_received_message_flag = 0;
	  }
  }

  return 0;
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  while (1)
  {
  }
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
extern "C" void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
  while(1)
  {}
}

/*
 * Minimal __assert() uses __assert__func()
 * */
extern "C" void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
